DEFINE 
MEASURE '_выбор_удельника'[Переключатель_удельник] = 

VAR Selection =

    SELECTEDVALUE ( '_выбор_удельника'[Type] )

RETURN

    SWITCH (
        TRUE (),
        Selection = "Удельник на услугу",           [Удельник_ОВИП],
        Selection = "Удельник на инсталляцию",      [Удельник общий на инсталляцию],
        Selection = "Удельник ГПХ+Штат+материалы",  [Удельник ГПХ+Штат+Материалы нараст корр период],
        Selection = "Удельник ГПХ+Штат ЧС",         [Удельник ГПХ+Штат ЧС корр период],
        Selection = "Удельник ГПХ+Штат МК",         [Удельник ГПХ+Штат МК корр период],
        Selection = "Удельник ГПХ+материалы",       [Удельник ГПХ + материалы корр период],
        Selection = "Удельник ГПХ",                 [Удельник ГПХ корр период],
		Selection = "Удельник ГПХ ЧС",              [Удельник ГПХ ЧС корр период],
        Selection = "Удельник ГПХ МК",              [Удельник ГПХ МК корр период],
        Selection = "Удельник ГПХ+материалы ЧС",    [Удельник ГПХ + материалы ЧС корр период],
        Selection = "Удельник ГПХ+материалы МК",    [Удельник ГПХ + материалы МК корр период],
        Selection = "Удельник Штат+материалы",      [Удельник Штат + материалы корр период],
		Selection = "Удельник Штат",                [Удельник Штат корр период],
		Selection = "Удельник Штат ЧС",             [Удельник Штат ЧС корр период],
        Selection = "Удельник Штат МК",             [Удельник Штат ЧС корр период],
        Selection = "Удельник Штат+материалы ЧС",   [Удельник Штат + материалы ЧС корр период],
        Selection = "Удельник Штат+материалы МК",   [Удельник Штат + материалы МК корр период],
        Selection = "Удельник Подряд",              [Удельник подряд],
        Selection = "Удельник Подряд ЧС",           [Удельник Подряд ЧС корр период],
        Selection = "Удельник Подряд МК",           [Удельник Подряд МК корр период],
        Selection = "Удельник на материалы",        [Удельник материалы],
        Selection = "Удельник на материалы ЧС",     [Удельник материалы ЧС],
        Selection = "Удельник на материалы МК",     [Удельник материалы МК],
		Selection = "Удельник B2C бюджет",          [Удельник_B2C_2020],
        Selection = "Удельник БТИ прогноз",         [Удельник_БТИ_срд],
        Selection = "Удельник МК",                  [Удельник МК корр период],
        Selection = "Удельник ЧС",                  [Удельник ЧС корр период],

        BLANK() 
)

